vich_uploader:
    db_driver: orm
    #on va enlever les commentaires pour faire fonctionner le service

    mappings:
        NewImage:
            uri_prefix: /images/
            upload_destination: "%kernel.project_dir%/public/images"
